# Generated by Django 4.0.4 on 2022-06-18 15:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщение',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image/news/')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('gLTF', models.FileField(upload_to='files/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('height', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('mini_title', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('adress', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.product')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='OrderUr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('inn', models.CharField(blank=True, default=0, max_length=14, verbose_name='ИНН паспорта')),
                ('okpo', models.CharField(blank=True, max_length=100, verbose_name='ОКПО')),
                ('bik', models.CharField(blank=True, max_length=100, verbose_name='БИК')),
                ('r_c', models.CharField(blank=True, max_length=100, verbose_name='р/с')),
                ('bank', models.CharField(blank=True, max_length=155, verbose_name='Банк')),
                ('director', models.CharField(max_length=255, verbose_name='Директор')),
                ('adress', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='+996', max_length=100)),
                ('grunt', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, default='Пусто', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemUr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.orderur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemFiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.orderur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('series', models.CharField(blank=True, max_length=7, verbose_name='серия пасспорта')),
                ('date_of_issue', models.DateField(blank=True, verbose_name='дата выдачи паспорта')),
                ('series_type', models.CharField(choices=[('ID', 'ID'), ('AN', 'AN')], default='ID', max_length=2, verbose_name='тип серии')),
                ('adress', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=100)),
                ('grunt', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, default='Пусто', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Image_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/works/')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.work')),
            ],
            options={
                'verbose_name': 'Фото работы',
                'verbose_name_plural': 'Фото работы',
            },
        ),
        migrations.CreateModel(
            name='Image_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.product')),
            ],
            options={
                'verbose_name': 'Фото Продукта',
                'verbose_name_plural': 'Фото Продуктов',
            },
        ),
        migrations.CreateModel(
            name='Image_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/news/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.news')),
            ],
            options={
                'verbose_name': 'Фото новости',
                'verbose_name_plural': 'Фото новости',
            },
        ),
    ]
