# Generated by Django 4.0.5 on 2022-06-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfiz',
            name='document',
            field=models.FileField(blank=True, default='/dogovor_ur.doc', null=True, upload_to='', verbose_name='upload/files/dogovory/'),
        ),
        migrations.AddField(
            model_name='orderur',
            name='document',
            field=models.FileField(blank=True, default='/dogovor_fiz.doc', null=True, upload_to='', verbose_name='upload/files/dogovory/'),
        ),
    ]
