# Generated by Django 4.0.5 on 2022-07-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_orderfiz_document_orderur_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderfiz',
            options={'ordering': ['-date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Физические Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderur',
            options={'ordering': ['-date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Юридические Заказы'},
        ),
        migrations.AddField(
            model_name='product',
            name='age_limit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='images/product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderur',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='upload/files/dogovory/'),
        ),
    ]
